### ISSUE TITLE
please reply

### ISSUE THREAD

**Issue by cht870422** [eggsampler/PCIeDMA#1]
Has your engineering project undergone sample testing?

**Comment by eggsampler** [comment]
No. Project needs to be reviewed and have some changes made before production.

**Comment by cht870422** [comment]
Less appearance, less drilling, less resistance welding,

**Comment by cht870422** [comment]
You can conduct a final error check on your project and submit an update. I can help you make samples and conduct testing If you have any needs, I can also send you a sample card by mail I live in China and manufacturing this hardware is very easy and affordable

**Comment by eggsampler** [comment]
I might have time to look at this over the Christmas break - what do you want to use it for>

**Comment by cht870422** [comment]
Thank you for taking the time to reply and be willing to conduct the final inspection for this project. I have a suggestion that this PCB can be changed from 8 layers to 4 layers. If you use a 4-layer circuit board, the production cost will be reduced. You can leave your mailing address or contact information for online communication. I suggest using WeChat because it supports translation, or you recommend a communication software

**Comment by Inzilkin** [comment]
@eggsampler, Hi. I see that the development process has started, any info on plans or timelines?

**Comment by eggsampler** [comment]
No solid plans or timelines, unless you have FPGA design experience.

**Comment by GRRENY** [comment]
> 感谢您抽出宝贵时间回复并愿意对本项目进行最终检查。我有一个建议，这个PCB可以从8层改成4层。如果使用4层电路板，生产成本会降低。您可以留下您的邮寄地址或联系信息以进行在线交流。我建议使用微信，因为它支持翻译，或者您推荐使用通信软件

Hello, I also live in China. May I ask which platform is the cheapest to produce samples?

**Comment by eggsampler** [comment]
I have no idea if this will even work yet, needs review.

**Comment by GRRENY** [comment]
Hello, thank you for the open source of the project. Have you finished reviewing these project materials? If you have reviewed it and it is correct, I am ready to produce a sample of the project. It is recommended that you leave your contact information, I have some questions I hope you can help me solve, thank you very much.

**Comment by GRRENY** [comment]
Can you add your contact details? Hope to communicate with you further

**Comment by eggsampler** [comment]
No communication required, needs to be reviewed by someone with fpga design experience.
