### ISSUE TITLE
Reaching Out

### ISSUE THREAD

**Issue by The30Note** [eggsampler/PCIeDMA#2]
Hey man this is sweet, I gotta love open source in a very restrictive and secretive community like this. Do you have any way I could get in touch? If you wanna reach out, my discord is t30n and my gmail is the same as my username here. Thanks!

**Comment by eggsampler** [comment]
Is there anything in particular you want to get in touch about?

**Comment by The30Note** [comment]
Nothing particular at the moment but I'd like to have a better way to communicate if I choose to peruse development of this board.
